[project]
name = "toms-data-scrubbing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tsteelematc", email = "tsteele@madisoncollege.edu" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
toms-data-scrubbing = "toms_data_scrubbing:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
